swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      tags:
        - Transaction Module
      summary: Récupérer les transactions du mois en cours par compte
      description: Retourne les transactions groupées par compte pour le mois en cours.
      parameters:
        - in: query
          name: userId
          description: ID de l'utilisateur
          required: true
          type: integer
        - in: query
          name: month
          description: Mois pour lequel récupérer les transactions (format MM/YYYY)
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Succès - Transactions récupérées avec succès
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Requête invalide - Vérifiez les paramètres
        '404':
          description: Utilisateur non trouvé - L'ID utilisateur spécifié n'existe pas
        '500':
          description: Erreur serveur - Impossible de traiter la requête

    post:
      tags:
        - Transaction Module
      summary: Ajouter une nouvelle transaction
      description: Ajoute une nouvelle transaction.
      parameters:
        - in: body
          name: body
          description: Données de la nouvelle transaction
          required: true
          schema:
            $ref: '#/definitions/NewTransaction'
      produces:
        - application/json
      responses:
        '201':
          description: Transaction ajoutée avec succès
          schema:
            $ref: '#/definitions/TransactionDetailResponse'
        '400':
          description: Requête invalide - Vérifiez les paramètres
        '500':
          description: Erreur serveur - Impossible de traiter la requête

    put: 
      tags:
        - Transaction Module
      summary: Ajouter une nouvelle transaction
      description: Ajoute une nouvelle transaction.
      parameters:
        - in: body
          name: body
          description: Données de la nouvelle transaction
          required: true
          schema:
            $ref: '#/definitions/NewTransaction'
      produces:
        - application/json
      responses:
        '201':
          description: Transaction ajoutée avec succès
          schema:
            $ref: '#/definitions/TransactionDetailResponse'
        '400':
          description: Requête invalide - Vérifiez les paramètres
        '500':
          description: Erreur serveur - Impossible de traiter la requête

  /transactions/{transactionId}:
    get:
      tags:
        - Transaction Module
      summary: Récupérer les détails d'une transaction
      description: Retourne les détails d'une transaction spécifique.
      parameters:
        - in: path
          name: transactionId
          description: ID de la transaction
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: Succès - Détails de la transaction récupérés avec succès
          schema:
            $ref: '#/definitions/TransactionDetailResponse'
        '404':
          description: Transaction non trouvée - L'ID de transaction spécifié n'existe pas
        '500':
          description: Erreur
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  