swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions/currentMonth:
    get:
      security: 
        - Bearer: []
      tags:
        - Transaction Module
      summary: Récupérer les transactions du mois en cours par compte
      description: Retourne les transactions groupées par compte pour le mois en cours.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true  
          type: string
        - in: query
          name: month
          description: Mois pour lequel récupérer les transactions (format MM/YYYY)
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Succès - Transactions récupérées avec succès
          schema:
            # $ref: '#/definitions/TransactionResponse'
            $ref: '#/definitions/currentMonth'
        '400':
          description: Requête invalide - Vérifiez les paramètres
        '500':
          description: Erreur serveur - Impossible de traiter la requête

  /transactions/{transactionId}:
    get:
      tags:
        - Transaction Module
      summary: Récupérer les détails d'une transaction
      description: Retourne les détails d'une transaction spécifique.
      parameters:
        - in: path
          name: transactionId
          description: ID de la transaction
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: Succès - Détails de la transaction récupérés avec succès
          schema:
            $ref: '#/definitions/UserTransactions'
        '404':
          description: Transaction non trouvée - L'ID de transaction spécifié n'existe pas
        '500':
          description: Erreur
  
  /transactions/editTransaction:
    patch:
      security: 
        - Bearer: []
      tags:
        - Transaction Module
      summary: Ajouter des informations sur une transaction
      description: Permets d'ajouter des informations à une transaction existante
      responses:
        '200':
          description: Succès - Transactions mise à jour avec succès
          schema:
            # $ref: '#/definitions/TransactionResponse'
            $ref: '#/definitions/UserTransactions'
        '400':
          description: Requête invalide - Vérifiez les paramètres
        '500':
          description: Erreur serveur - Impossible de traiter la requête
    put: 
      security: 
        - Bearer: []
      tags:
        - Transaction Module
      summary: Modifier des informations sur une transaction
      description: Permets de Modifier des informations (voir l'effacer) d'une transaction existante
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true  
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Succès - Transactions modifiée avec succès
          schema:
            # $ref: '#/definitions/TransactionResponse'
            $ref: '#/definitions/UserTransactions'
        '400':
          description: Requête invalide - Vérifiez les paramètres
        '500':
          description: Erreur serveur - Impossible de traiter la requête
    
definitions:
  currentMonth:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string 
  UserTransactions:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string 